import express from 'express';
import cors from 'cors';
import multer from 'multer';
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join, extname } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const DATA_PATH = join(__dirname, '..', 'src', 'data', 'siteData.json');
const UPLOAD_DIR = join(__dirname, '..', 'public', 'uploads');

if (!existsSync(UPLOAD_DIR)) mkdirSync(UPLOAD_DIR, { recursive: true });

// ============================================================
// ADMIN CREDENTIALS — Change these!
// ============================================================
const ADMIN_USER = 'admin';
const ADMIN_PASS = 'ies2026secure';
const API_TOKEN = 'ies-admin-token-x7k9m2p4';

const app = express();
app.use(cors());
app.use(express.json({ limit: '10mb' }));
app.use('/uploads', express.static(UPLOAD_DIR));

// Multer config for image uploads
const storage = multer.diskStorage({
  destination: (req, file, cb) => cb(null, UPLOAD_DIR),
  filename: (req, file, cb) => {
    const unique = Date.now() + '-' + Math.round(Math.random() * 1e6);
    cb(null, unique + extname(file.originalname));
  }
});
const upload = multer({
  storage,
  limits: { fileSize: 10 * 1024 * 1024 },
  fileFilter: (req, file, cb) => {
    const allowed = ['.jpg', '.jpeg', '.png', '.gif', '.webp', '.svg'];
    cb(null, allowed.includes(extname(file.originalname).toLowerCase()));
  }
});

function readData() {
  if (!existsSync(DATA_PATH)) {
    writeFileSync(DATA_PATH, JSON.stringify({}, null, 2), 'utf-8');
  }
  return JSON.parse(readFileSync(DATA_PATH, 'utf-8'));
}

function writeData(data) {
  writeFileSync(DATA_PATH, JSON.stringify(data, null, 2), 'utf-8');
  const jsPath = join(__dirname, '..', 'src', 'data', 'siteData.js');
  const jsContent = `// Auto-generated by admin panel\nconst D = ${JSON.stringify(data, null, 2)};\nexport default D;\n`;
  writeFileSync(jsPath, jsContent, 'utf-8');
}

function auth(req, res, next) {
  const token = req.headers.authorization?.replace('Bearer ', '');
  if (token !== API_TOKEN) return res.status(401).json({ error: 'Unauthorized' });
  next();
}

// Login
app.post('/api/login', (req, res) => {
  const { username, password } = req.body;
  if (username === ADMIN_USER && password === ADMIN_PASS) {
    return res.json({ token: API_TOKEN });
  }
  res.status(401).json({ error: 'Invalid credentials' });
});

// Get data
app.get('/api/data', auth, (req, res) => res.json(readData()));

// Update entire data
app.put('/api/data', auth, (req, res) => {
  try { writeData(req.body); res.json({ success: true }); }
  catch (e) { res.status(500).json({ error: e.message }); }
});

// Update section
app.patch('/api/data/:section', auth, (req, res) => {
  try {
    const data = readData();
    const section = req.params.section;
    if (section.includes('.')) {
      const parts = section.split('.');
      let obj = data;
      for (let i = 0; i < parts.length - 1; i++) obj = obj[parts[i]];
      obj[parts[parts.length - 1]] = req.body.value;
    } else {
      data[section] = req.body.value;
    }
    writeData(data);
    res.json({ success: true });
  } catch (e) { res.status(500).json({ error: e.message }); }
});

// Image upload
app.post('/api/upload', auth, upload.single('image'), (req, res) => {
  if (!req.file) return res.status(400).json({ error: 'No file uploaded' });
  const url = `/uploads/${req.file.filename}`;
  res.json({ url });
});

const PORT = 3001;
app.listen(PORT, () => console.log(`Admin API running on http://localhost:${PORT}`));
