import{useState}from"react";import{getTheme}from"../data/theme";import D from"../data/siteData";import I from"../components/Icons";import{PhotoPlaceholder,Section,SectionHeader,Breadcrumbs}from"../components/Section";
const TABS=[{k:"professor",l:"Professor"},{k:"seniorResearchers",l:"Senior Researchers"},{k:"phdStudents",l:"PhD Students"},{k:"secretary",l:"Secretary"}];
export default function MembersPage({dark,navigate}){const t=getTheme(dark);const[tab,setTab]=useState("professor");const[q,setQ]=useState("");
const ms=(D.members[tab]||[]).filter(m=>m.name.toLowerCase().includes(q.toLowerCase())||m.topics?.some(tp=>tp.toLowerCase().includes(q.toLowerCase()))||m.role?.toLowerCase().includes(q.toLowerCase()));

return<div style={{paddingTop:86}}><Section dark={dark}>
<Breadcrumbs items={[{label:"Home",href:"home"},{label:"Members"}]} dark={dark} navigate={navigate}/>
<SectionHeader title="Members" subtitle="Meet the team behind our research" dark={dark}/>
<div style={{display:"flex",alignItems:"center",gap:8,background:t.sB,borderRadius:8,padding:"9px 14px",marginBottom:20,border:`1px solid ${t.bd}`,maxWidth:380}}><span style={{color:t.txD}}>{I.search}</span><input type="text" placeholder="Search members..." value={q} onChange={e=>setQ(e.target.value)} style={{background:"transparent",border:"none",outline:"none",fontSize:13,color:t.tx,width:"100%",fontFamily:"inherit"}}/></div>
<div style={{display:"flex",gap:4,marginBottom:32,flexWrap:"wrap"}}>{TABS.map(tb=><button key={tb.k} onClick={()=>setTab(tb.k)} style={{background:tab===tb.k?t.ac:"transparent",color:tab===tb.k?"#fff":t.txM,border:`1px solid ${tab===tb.k?t.ac:t.bd}`,padding:"6px 16px",borderRadius:99,fontSize:12,fontWeight:tab===tb.k?600:400,cursor:"pointer",fontFamily:"inherit"}}>{tb.l}</button>)}</div>

{ms.length===0?<p style={{color:t.txM,fontSize:13}}>No members found{q?" matching your search":" in this category yet"}.</p>

/* ===== PROFESSOR ===== */
:tab==="professor"?ms.map((m,i)=><div key={i} style={{background:t.bgC,borderRadius:18,border:`1px solid ${t.bd}`,overflow:"hidden"}}><div style={{display:"flex",flexWrap:"wrap"}}><div style={{width:"min(100%,300px)",minHeight:300,overflow:"hidden"}}>{m.photo?<img src={m.photo} alt={m.name} style={{width:"100%",height:"100%",objectFit:"cover"}}/>:<PhotoPlaceholder name={m.name} size={160}/>}</div><div style={{flex:1,padding:"28px 32px",minWidth:260}}><h3 style={{fontSize:26,fontWeight:700,color:t.tx,margin:0,marginBottom:14}}>{m.name}</h3><p style={{fontSize:14,fontWeight:500,color:t.ac,margin:0,marginBottom:12}}>{m.bio?.headline}</p><p style={{fontSize:13,color:t.txM,lineHeight:1.7,margin:0,marginBottom:16}}>{m.bio?.summary}</p><div style={{display:"flex",flexDirection:"column",gap:8,marginBottom:20}}>{m.bio?.highlights?.map((h,j)=><div key={j} style={{display:"flex",gap:6,alignItems:"baseline"}}><span style={{fontWeight:600,fontSize:12,color:t.tx}}>{h.label}:</span><span style={{fontSize:12,color:t.txM}}>{h.detail}</span></div>)}</div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><button onClick={()=>navigate("professor-profile")} style={{display:"inline-flex",alignItems:"center",gap:5,background:t.ac,border:"none",borderRadius:99,padding:"9px 20px",color:"#fff",fontSize:12,fontWeight:600,cursor:"pointer",fontFamily:"inherit"}}>{I.user} Website</button>{m.email&&<button style={{display:"inline-flex",alignItems:"center",gap:5,background:t.tg,border:`1px solid ${t.bd}`,borderRadius:99,padding:"9px 20px",color:t.ac,fontSize:12,cursor:"pointer",fontFamily:"inherit"}}>{I.mail} {m.email}</button>}</div></div></div></div>)

/* ===== SECRETARY — compact 2-column ===== */
:tab==="secretary"?<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(min(100%,400px),1fr))",gap:14}}>
  {ms.map((m,i)=><div key={i} style={{background:t.bgC,borderRadius:12,border:`1px solid ${t.bd}`,padding:16,display:"flex",gap:14,alignItems:"center"}}>
    {m.photo?<img src={m.photo} alt={m.name} style={{width:64,height:80,borderRadius:10,objectFit:"cover",flexShrink:0}}/>:<PhotoPlaceholder name={m.name} size={64}/>}
    <div style={{flex:1,minWidth:0}}>
      <h4 style={{fontSize:15,fontWeight:600,color:t.tx,margin:0,marginBottom:3}}>{m.name}</h4>
      <p style={{fontSize:12,color:t.txM,margin:0,marginBottom:6}}>{m.role}</p>
      {m.email&&<a href={`mailto:${m.email}`} style={{display:"flex",alignItems:"center",gap:5,fontSize:12,color:t.ac,textDecoration:"underline",textUnderlineOffset:3}}>{I.mail}{m.email}</a>}
    </div>
  </div>)}
</div>

/* ===== PHD STUDENTS — big cards ===== */
:tab==="phdStudents"?<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(min(100%,360px),1fr))",gap:16}}>{ms.map((m,i)=><div key={i} style={{background:t.bgC,borderRadius:14,border:`1px solid ${t.bd}`,overflow:"hidden"}}><div style={{display:"flex",gap:16,padding:20}}>{m.photo?<img src={m.photo} alt={m.name} style={{width:90,height:110,borderRadius:10,objectFit:"cover"}}/>:<PhotoPlaceholder name={m.name} size={90}/>}<div style={{flex:1,minWidth:0}}><h4 style={{fontSize:16,fontWeight:600,color:t.tx,margin:0,marginBottom:6}}>{m.name}</h4><div style={{display:"flex",flexDirection:"column",gap:3}}>{m.topics?.map((tp,j)=><div key={j} style={{display:"flex",alignItems:"center",gap:4,fontSize:12,color:t.txM}}><div style={{width:4,height:4,borderRadius:"50%",background:t.ac,flexShrink:0}}/>{tp}</div>)}</div></div></div><div style={{borderTop:`1px solid ${t.bd}`,padding:"12px 20px"}}>{m.email&&<div style={{display:"flex",alignItems:"center",gap:6,fontSize:12,color:t.txD,marginBottom:8}}>{I.mail}<a href={`mailto:${m.email}`} style={{color:t.ac,textDecoration:"underline",textUnderlineOffset:3}}>{m.email}</a></div>}{m.references&&<div style={{display:"flex",alignItems:"center",gap:6,fontSize:12,color:t.txD}}>{I.ref}<a href={m.references} style={{color:t.ac,textDecoration:"underline",textUnderlineOffset:3}}>References</a></div>}</div></div>)}</div>

/* ===== SENIOR RESEARCHERS — same big style as PhD ===== */
:<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(min(100%,360px),1fr))",gap:16}}>{ms.map((m,i)=><div key={i} style={{background:t.bgC,borderRadius:14,border:`1px solid ${t.bd}`,overflow:"hidden"}}><div style={{display:"flex",gap:16,padding:20}}>{m.photo?<img src={m.photo} alt={m.name} style={{width:90,height:110,borderRadius:10,objectFit:"cover"}}/>:<PhotoPlaceholder name={m.name} size={90}/>}<div style={{flex:1,minWidth:0}}><h4 style={{fontSize:16,fontWeight:600,color:t.tx,margin:0,marginBottom:6}}>{m.name}</h4><div style={{display:"flex",flexDirection:"column",gap:3}}>{m.topics?.map((tp,j)=><div key={j} style={{display:"flex",alignItems:"center",gap:4,fontSize:12,color:t.txM}}><div style={{width:4,height:4,borderRadius:"50%",background:t.ac,flexShrink:0}}/>{tp}</div>)}</div></div></div><div style={{borderTop:`1px solid ${t.bd}`,padding:"12px 20px"}}>{m.email&&<div style={{display:"flex",alignItems:"center",gap:6,fontSize:12,color:t.txD}}>{I.mail}<a href={`mailto:${m.email}`} style={{color:t.ac,textDecoration:"underline",textUnderlineOffset:3}}>{m.email}</a></div>}</div></div>)}</div>}
</Section></div>;}
