import{getTheme}from"../data/theme";import D from"../data/siteData";import I from"./Icons";import{Section,SectionHeader}from"./Section";

export function AboutSection({dark}){const t=getTheme(dark);return<Section dark={dark}><SectionHeader title="About" dark={dark}/><div style={{display:"grid",gridTemplateColumns:"1fr minmax(0,380px)",gap:28,alignItems:"start"}} className="ab-g"><div style={{display:"flex",flexDirection:"column",gap:16}}>{D.about.paragraphs.map((p,i)=><div key={i} style={{padding:22,borderRadius:12,background:t.bgC,border:`1px solid ${t.bd}`}}><p style={{fontSize:13,color:t.txM,lineHeight:1.75,margin:0}}>{p}</p></div>)}</div><div style={{borderRadius:16,overflow:"hidden",height:"100%",minHeight:280}}><img src={D.about.image} alt="IES Lab" style={{width:"100%",height:"100%",objectFit:"cover"}}/></div></div><style>{`.ab-g{@media(max-width:720px){grid-template-columns:1fr!important}}`}</style></Section>;}

export function NewsSection({dark,navigate}){const t=getTheme(dark);return<Section dark={dark} alt><SectionHeader title="Latest News" subtitle="Recent highlights from the IES Lab" dark={dark}/><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(min(100%,300px),1fr))",gap:16}}>{D.news.map(n=><div key={n.id} style={{background:t.bgC,borderRadius:14,overflow:"hidden",border:`1px solid ${t.bd}`,cursor:"pointer"}}><div style={{height:160,position:"relative",overflow:"hidden"}}><img src={n.image} alt={n.title} style={{width:"100%",height:"100%",objectFit:"cover"}}/><div style={{position:"absolute",inset:0,background:`linear-gradient(to top,${n.color}40,transparent)`}}/></div><div style={{padding:"18px 20px 20px"}}><h3 style={{fontSize:15,fontWeight:600,color:t.tx,margin:0,marginBottom:6}}>{n.title}</h3><p style={{fontSize:12,color:t.txM,lineHeight:1.6,margin:0,marginBottom:10}}>{n.description}</p><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div style={{display:"flex",gap:10,fontSize:11,color:t.txD}}><span>{n.date}</span><span>·</span><span>{n.location}</span></div>{n.title==="Open Position"&&<button onClick={e=>{e.stopPropagation();navigate("positions");}} style={{display:"inline-flex",alignItems:"center",gap:4,background:t.tg,border:`1px solid ${t.bd}`,borderRadius:99,padding:"5px 12px",color:t.ac,fontSize:10,fontWeight:600,cursor:"pointer",fontFamily:"inherit"}}>More Positions {I.arrow}</button>}</div></div></div>)}</div></Section>;}

export function AllianceSection({dark}){const t=getTheme(dark);return<Section dark={dark}><SectionHeader title="Strategic Alliance" dark={dark}/><div style={{background:t.alBg,borderRadius:18,overflow:"hidden",display:"flex",flexWrap:"wrap"}}><div style={{width:"min(100%,360px)",minHeight:240}}><img src={D.alliance.image} alt="Hahn-Schickard" style={{width:"100%",height:"100%",objectFit:"cover"}}/></div><div style={{flex:1,padding:"clamp(24px,4vw,44px)",minWidth:260,display:"flex",flexDirection:"column",justifyContent:"center"}}><h3 style={{fontSize:"clamp(20px,3vw,28px)",fontWeight:600,color:"#fff",margin:0,marginBottom:10}}>{D.alliance.name}</h3><p style={{fontSize:14,color:"rgba(255,255,255,0.65)",lineHeight:1.7,maxWidth:500,margin:0,marginBottom:18}}>{D.alliance.description}</p><button style={{display:"inline-flex",alignItems:"center",gap:6,background:"rgba(255,255,255,0.1)",border:"1px solid rgba(255,255,255,0.15)",borderRadius:99,padding:"8px 18px",color:"#fff",fontSize:12,cursor:"pointer",fontFamily:"inherit",width:"fit-content"}}>Learn more {I.arrow}</button></div></div></Section>;}

// Team photo banner — standalone section
export function TeamBanner({dark}){
  const t=getTheme(dark);
  return<div style={{position:"relative",height:"clamp(200px,28vw,340px)",overflow:"hidden"}}>
    <img src={D.groupPhoto} alt="IES Lab Team" style={{width:"100%",height:"100%",objectFit:"cover"}}/>
    <div style={{position:"absolute",inset:0,background:"linear-gradient(to right,rgba(11,15,26,0.75),rgba(11,15,26,0.25))",display:"flex",alignItems:"center",padding:"0 24px"}}>
      <div style={{maxWidth:1200,margin:"0 auto",width:"100%"}}>
        <p style={{fontSize:"clamp(18px,3vw,28px)",fontWeight:600,color:"#fff",margin:0}}>Our Team</p>
        <p style={{fontSize:14,color:"rgba(255,255,255,0.6)",marginTop:6}}>Researchers, engineers, and students working together at the IES Lab</p>
      </div>
    </div>
  </div>;
}

export function StudentProjectsPreview({dark,navigate}){const t=getTheme(dark);return<Section dark={dark} alt><SectionHeader title="Student Projects" subtitle="Current research opportunities" dark={dark}/><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(min(100%,220px),1fr))",gap:12,marginBottom:24}}>{D.studentProjects.map(p=><div key={p.id} onClick={()=>navigate("projects")} style={{background:t.bgC,borderRadius:12,overflow:"hidden",border:`1px solid ${t.bd}`,cursor:"pointer"}}><div style={{height:100,overflow:"hidden"}}><img src={p.image} alt={p.shortTitle} style={{width:"100%",height:"100%",objectFit:"cover"}}/></div><div style={{padding:"14px 16px 16px"}}><h4 style={{fontSize:13,fontWeight:600,color:t.tx,margin:0,marginBottom:4}}>{p.shortTitle}</h4><p style={{fontSize:11,color:t.txM,lineHeight:1.5,margin:0,display:"-webkit-box",WebkitLineClamp:2,WebkitBoxOrient:"vertical",overflow:"hidden"}}>{p.title}</p></div></div>)}</div><button onClick={()=>navigate("projects")} style={{display:"inline-flex",alignItems:"center",gap:6,background:t.tg,border:`1px solid ${t.bd}`,borderRadius:99,padding:"10px 22px",color:t.ac,fontSize:13,fontWeight:600,cursor:"pointer",fontFamily:"inherit"}}>More Projects {I.arrow}</button></Section>;}

export function ResearchSection({dark,navigate}){const t=getTheme(dark);return<Section dark={dark}><SectionHeader title="Research Areas" subtitle="Core domains of investigation" dark={dark}/><div style={{display:"flex",flexDirection:"column",gap:14}}>{D.researchAreas.map((a,i)=><div key={a.id} onClick={()=>navigate("research-"+a.id)} style={{borderRadius:14,overflow:"hidden",cursor:"pointer",position:"relative",minHeight:200,display:"flex",alignItems:"flex-end"}}><img src={a.image} alt={a.title} style={{position:"absolute",inset:0,width:"100%",height:"100%",objectFit:"cover"}}/><div style={{position:"absolute",inset:0,background:a.gradient,opacity:0.85}}/><div style={{position:"relative",padding:"clamp(22px,3.5vw,36px)",width:"100%"}}><h3 style={{fontSize:"clamp(18px,2.5vw,26px)",fontWeight:600,color:"#fff",margin:0,marginBottom:4}}>{a.title}</h3><p style={{fontSize:13,color:"rgba(255,255,255,0.6)",margin:0,marginBottom:14}}>{a.subtitle}</p><span style={{display:"inline-flex",alignItems:"center",gap:5,fontSize:12,color:"rgba(255,255,255,0.75)"}}>Explore {I.arrow}</span></div></div>)}</div></Section>;}
